# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from App.Services import doctor_pb2 as doctor__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in doctor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DoctorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAvailableDoctors = channel.unary_unary(
                '/doctor.DoctorService/GetAvailableDoctors',
                request_serializer=doctor__pb2.AvailableDoctorsRequest.SerializeToString,
                response_deserializer=doctor__pb2.AvailableDoctorsResponse.FromString,
                _registered_method=True)
        self.GetDoctorById = channel.unary_unary(
                '/doctor.DoctorService/GetDoctorById',
                request_serializer=doctor__pb2.DoctorIdRequest.SerializeToString,
                response_deserializer=doctor__pb2.DoctorResponse.FromString,
                _registered_method=True)


class DoctorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAvailableDoctors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDoctorById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DoctorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAvailableDoctors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableDoctors,
                    request_deserializer=doctor__pb2.AvailableDoctorsRequest.FromString,
                    response_serializer=doctor__pb2.AvailableDoctorsResponse.SerializeToString,
            ),
            'GetDoctorById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDoctorById,
                    request_deserializer=doctor__pb2.DoctorIdRequest.FromString,
                    response_serializer=doctor__pb2.DoctorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'doctor.DoctorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('doctor.DoctorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DoctorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAvailableDoctors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doctor.DoctorService/GetAvailableDoctors',
            doctor__pb2.AvailableDoctorsRequest.SerializeToString,
            doctor__pb2.AvailableDoctorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDoctorById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/doctor.DoctorService/GetDoctorById',
            doctor__pb2.DoctorIdRequest.SerializeToString,
            doctor__pb2.DoctorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
