version: '3.8'

services:
  # Dịch vụ NotificationService
  notificationservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification_service_app
    ports:
      - "8088:80"
    environment:
      # Cấu hình môi trường ASP.NET Core
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"

      # Cấu hình kết nối MongoDB
      MongoDBSettings__ConnectionString: "mongodb://mongodb:27017"
      MongoDBSettings__DatabaseName: "notificationdb"
      MongoDBSettings__CollectionName: "notifications"

      # Cấu hình kết nối RabbitMQ 
      RabbitMQ__AmqpConnectionString: "amqps://errymwix:JCnl3C8qXN32qdFwK7B9hM-Dfn9SLrNb@armadillo.rmq.cloudamqp.com/errymwix"
      "QueueName": "appointment_queue"

      # Cấu hình cài đặt Email
      MailSettings__SenderName: "ABC Hospital App"
      MailSettings__SenderEmail: "kantruong11@gmail.com"
      MailSettings__SmtpHost: "smtp.example.com"
      MailSettings__SmtpPort: 587
      MailSettings__SmtpUsername: "kantruong11@gmail.com"
      MailSettings__SmtpPassword: "jvwq swtn icua jlde"
    
    depends_on:
      - mongodb
      - rabbitmq

  # Dịch vụ MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db 

  # Dịch vụ RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_server
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongodb_data:
  rabbitmq_data: