# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: appointment.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'appointment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61ppointment.proto\x12\x0b\x61ppointment\".\n\x14\x41ppointmentIdRequest\x12\x16\n\x0e\x61ppointment_id\x18\x01 \x01(\x05\"\xac\x01\n\x13\x41ppointmentResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x16\n\x0e\x61ppointment_id\x18\x02 \x01(\x05\x12\x12\n\npatient_id\x18\x03 \x01(\x05\x12\x11\n\tdoctor_id\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x07 \x01(\t\x12\x14\n\x0cstarted_time\x18\x08 \x01(\t2o\n\x12\x41ppointmentService\x12Y\n\x12GetAppointmentById\x12!.appointment.AppointmentIdRequest\x1a .appointment.AppointmentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'appointment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPOINTMENTIDREQUEST']._serialized_start=34
  _globals['_APPOINTMENTIDREQUEST']._serialized_end=80
  _globals['_APPOINTMENTRESPONSE']._serialized_start=83
  _globals['_APPOINTMENTRESPONSE']._serialized_end=255
  _globals['_APPOINTMENTSERVICE']._serialized_start=257
  _globals['_APPOINTMENTSERVICE']._serialized_end=368
# @@protoc_insertion_point(module_scope)
