# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: doctor.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'doctor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64octor.proto\x12\x06\x64octor\"$\n\x0f\x44octorIdRequest\x12\x11\n\tdoctor_id\x18\x01 \x01(\t\"\xca\x01\n\x0e\x44octorResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x11\n\tdoctor_id\x18\x02 \x01(\t\x12\x15\n\ridentity_card\x18\x03 \x01(\t\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x10\n\x08\x66ullname\x18\x05 \x01(\t\x12\x12\n\nbirth_date\x18\x06 \x01(\t\x12\x0e\n\x06gender\x18\x07 \x01(\t\x12\x14\n\x0cphone_number\x18\x08 \x01(\t\x12\r\n\x05\x65mail\x18\t \x01(\t\x12\x12\n\ndepartment\x18\n \x01(\t\"B\n\x17\x41vailableDoctorsRequest\x12\x13\n\x0b\x65xcluded_id\x18\x01 \x03(\t\x12\x12\n\ndepartment\x18\x02 \x01(\t\"C\n\x18\x41vailableDoctorsResponse\x12\'\n\x07\x64octors\x18\x01 \x03(\x0b\x32\x16.doctor.DoctorResponse2\xab\x01\n\rDoctorService\x12X\n\x13GetAvailableDoctors\x12\x1f.doctor.AvailableDoctorsRequest\x1a .doctor.AvailableDoctorsResponse\x12@\n\rGetDoctorById\x12\x17.doctor.DoctorIdRequest\x1a\x16.doctor.DoctorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'doctor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOCTORIDREQUEST']._serialized_start=24
  _globals['_DOCTORIDREQUEST']._serialized_end=60
  _globals['_DOCTORRESPONSE']._serialized_start=63
  _globals['_DOCTORRESPONSE']._serialized_end=265
  _globals['_AVAILABLEDOCTORSREQUEST']._serialized_start=267
  _globals['_AVAILABLEDOCTORSREQUEST']._serialized_end=333
  _globals['_AVAILABLEDOCTORSRESPONSE']._serialized_start=335
  _globals['_AVAILABLEDOCTORSRESPONSE']._serialized_end=402
  _globals['_DOCTORSERVICE']._serialized_start=405
  _globals['_DOCTORSERVICE']._serialized_end=576
# @@protoc_insertion_point(module_scope)
