# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: medicine.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'medicine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emedicine.proto\x12\x08medicine\"(\n\x11MedicineIdRequest\x12\x13\n\x0bmedicine_id\x18\x01 \x01(\x05\"<\n\x15UpdateMedicineRequest\x12\x13\n\x0bmedicine_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"\x8b\x01\n\x10MedicineResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x13\n\x0bmedicine_id\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0b\n\x03MFG\x18\x04 \x01(\t\x12\x0b\n\x03\x45XP\x18\x05 \x01(\t\x12\x0c\n\x04unit\x18\x06 \x01(\t\x12\r\n\x05price\x18\x07 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x08 \x01(\x05\x32\xac\x01\n\x0fMedicineService\x12J\n\x0fGetMedicineById\x12\x1b.medicine.MedicineIdRequest\x1a\x1a.medicine.MedicineResponse\x12M\n\x0eUpdateMedicine\x12\x1f.medicine.UpdateMedicineRequest\x1a\x1a.medicine.MedicineResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'medicine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEDICINEIDREQUEST']._serialized_start=28
  _globals['_MEDICINEIDREQUEST']._serialized_end=68
  _globals['_UPDATEMEDICINEREQUEST']._serialized_start=70
  _globals['_UPDATEMEDICINEREQUEST']._serialized_end=130
  _globals['_MEDICINERESPONSE']._serialized_start=133
  _globals['_MEDICINERESPONSE']._serialized_end=272
  _globals['_MEDICINESERVICE']._serialized_start=275
  _globals['_MEDICINESERVICE']._serialized_end=447
# @@protoc_insertion_point(module_scope)
