# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: patient.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'patient.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpatient.proto\x12\x07patient\"&\n\x10PatientIdRequest\x12\x12\n\npatient_id\x18\x01 \x01(\x05\"/\n\x16PatientIdentityRequest\x12\x15\n\ridentity_card\x18\x01 \x01(\t\"\xc8\x01\n\x0fPatientResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x15\n\ridentity_card\x18\x03 \x01(\t\x12\x10\n\x08\x66ullname\x18\x04 \x01(\t\x12\x12\n\nbirth_date\x18\x05 \x01(\t\x12\x0e\n\x06gender\x18\x06 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x07 \x01(\t\x12\x14\n\x0cphone_number\x18\x08 \x01(\t\x12\r\n\x05\x65mail\x18\t \x01(\t\x12\x17\n\x0fmedical_history\x18\n \x01(\t2\xaa\x01\n\x0ePatientService\x12\x45\n\x0eGetPatientById\x12\x19.patient.PatientIdRequest\x1a\x18.patient.PatientResponse\x12Q\n\x14GetPatientByIdentity\x12\x1f.patient.PatientIdentityRequest\x1a\x18.patient.PatientResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'patient_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PATIENTIDREQUEST']._serialized_start=26
  _globals['_PATIENTIDREQUEST']._serialized_end=64
  _globals['_PATIENTIDENTITYREQUEST']._serialized_start=66
  _globals['_PATIENTIDENTITYREQUEST']._serialized_end=113
  _globals['_PATIENTRESPONSE']._serialized_start=116
  _globals['_PATIENTRESPONSE']._serialized_end=316
  _globals['_PATIENTSERVICE']._serialized_start=319
  _globals['_PATIENTSERVICE']._serialized_end=489
# @@protoc_insertion_point(module_scope)
